apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lm5lh3b53-nodejs 
  janus-idp.io/tekton: lm5lh3b53-nodejs
  backstage.io/kubernetes-id: lm5lh3b53-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lm5lh3b53-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml